<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace vitor_test\Acme\Models\Operations;

use \vitor_test\Acme\Utils\SpeakeasyMetadata;
class UpdateUserv1Request
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \vitor_test\Acme\Models\Shared\UserInput $userInput;
    
    /**
     * UserID
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->userInput = new \vitor_test\Acme\Models\Shared\UserInput();
		$this->id = "";
	}
}
