<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace vitor_test\Acme\Models\Components;


/**
 * Filter - Filters are used to query requests.
 * 
 * @package vitor_test\Acme\Models\Components
 * @access public
 */
class Filter
{
	#[\JMS\Serializer\Annotation\SerializedName('field')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $field;
    
	#[\JMS\Serializer\Annotation\SerializedName('matchtype')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $matchtype;
    
	#[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $value;
    
	public function __construct()
	{
		$this->field = "";
		$this->matchtype = "";
		$this->value = "";
	}
}
