<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace vitor_test\Acme\Models\Components;


/**
 * UserInput - The details of a typical user account
 * 
 * @package vitor_test\Acme\Models\Components
 * @access public
 */
class UserInput
{
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $country;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
	#[\JMS\Serializer\Annotation\SerializedName('firstname')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $firstname;
    
	#[\JMS\Serializer\Annotation\SerializedName('lastname')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastname;
    
	#[\JMS\Serializer\Annotation\SerializedName('nickname')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $nickname;
    
	#[\JMS\Serializer\Annotation\SerializedName('password')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $password;
    
	public function __construct()
	{
		$this->country = "";
		$this->email = "";
		$this->firstname = "";
		$this->lastname = "";
		$this->nickname = "";
		$this->password = "";
	}
}
