<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace vitor_test\Acme\Models\Components;


/**
 * Users - An array of users.
 * 
 * @package vitor_test\Acme\Models\Components
 * @access public
 */
class Users
{
    /**
     * A list of users to return.
     * 
     * @var array<\vitor_test\Acme\Models\Components\User> $users
     */
	#[\JMS\Serializer\Annotation\SerializedName('users')]
    #[\JMS\Serializer\Annotation\Type('array<vitor_test\Acme\Models\Components\User>')]
    public array $users;
    
	public function __construct()
	{
		$this->users = [];
	}
}
