<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace vitor_test\Acme;

class SDKConfiguration
{
	public ?\GuzzleHttp\ClientInterface $defaultClient = null;
	public ?\GuzzleHttp\ClientInterface $securityClient = null;
	
	public string $serverUrl = '';
	public int $serverIndex = 0;
	public string $language = 'php';
	public string $openapiDocVersion = '0.1.0';
	public string $sdkVersion = '0.1.0';
	public string $genVersion = '2.272.4';
	public string $userAgent = 'speakeasy-sdk/php 0.1.0 2.272.4 0.1.0 vitor-test/acme-go/test';
	

	public function getServerUrl(): string
	{
		
		if ($this->serverUrl !== '') {
			return $this->serverUrl;
		};
		return AcmeGo::SERVERS[$this->serverIndex];
	}
	
}